import dotenv from "dotenv";
dotenv.config();
const {
  PORT,
  CLIENT_URL,
  MONGODB_URI,
  JWT_SECRET_ACCESS_TOKEN,
  JWT_EXPIRES_IN,
  JWT_EXPIRES_REFRESH_EXPIRES_IN,
  JWT_EXPIRES_REFRESH_SECRET,
  NODE_ENV,
  EMAIL,
  EMAIL_PASSWORD,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
} = process.env;

export const config = {
  PORT,
  CLIENT_URL,
  MONGODB_URI,
  JWT_SECRET_ACCESS_TOKEN,
  JWT_EXPIRES_IN,
  JWT_EXPIRES_REFRESH_EXPIRES_IN,
  JWT_EXPIRES_REFRESH_SECRET,
  NODE_ENV,
  EMAIL,
  EMAIL_PASSWORD,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
};
//Reset-Password then OTP &&
